apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  initContainers:
  - name: init-container
    image: busybox:1.32.0
    command: ['sh', '-c', 'echo "Initialization completed" > /workdir/initfile']
    volumeMounts:
    - name: workdir-volume
      mountPath: /workdir

  containers:
  - name: main-container
    image: busybox:1.32.0
    command: ['sh', '-c', 'cat /workdir/initfile && sleep 3600']
    volumeMounts:
    - name: workdir-volume
      mountPath: /workdir

  volumes:
  - name: workdir-volume
    emptyDir: {}
