apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  #App container
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: data
        mountPath: /usr/share/nginx/html
  #This is extra container
  - name: extra-container
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date > /usr/share/nginx/html/index.html;
          sleep 1;
        done
    volumeMounts:
      - name: data
        mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      emptyDir: {}
